* datapp
** Goals
- provide the tools to make an app as data
- provide everything in between calling functions between a Clojure server and Clojurescript webapp
- as little as possible "template" code - the stuff that gets copy-pasted to get a project started
  - in a reasonable manner; it should still make sense and not be a macro monstrosity
  - with preference to having the stuff that does get copy-pasted very unlikely to change (eg. project settings)
** Motivation
This is meant to solve two problems for me.

First: I find myself, when making a quick new project for a hackathon or a quick prototype, copy-pasting a ton of code. This is quite annoying because now I have to maintain that code, and when I make improvements to it, I basically have to copy-paste it into all projects with a similar structure (if I'm still maintaining them). Why not factor our the reusable part of webapps?

Second: Decomplecting all of this stuff from business logic. This is separate logic, so it should be kept separate to make it easy to follow best practices.

It seems like there are other attempts to solve this problem, but they mostly involve templates (which solves neither problem, it just makes it easier to get started). Hopefully, it can help others who feel the same.
* TODOs
- more sugar in merging into the system map
- try resources with in library?
- reagent / reagent utils
  - with nashorn + generating html serverside
- scss
- timer
- websocket
- authentication
  - DIY with session
  - mongo session
  - friend
- cljs repl
- browser repl
- db modules
  - mongodb
  - datomic?
  - postgres
    - korma
    - [[https://github.com/alaisi/postgres.async][postgres.async]]
- cordova
  - APNS
  - GCM
  - make-updating-app
  - make-static-app
- testing
- heroku/docker setup?
- study
  - luminus
    - http://yogthos.net/#/blog/35-Luminus:+a+web+framework+for+Clojure
    - https://github.com/yogthos/luminus-template
    - http://www.luminusweb.net/
  - pedestal
    - https://github.com/pedestal/pedestal
    - http://teropa.info/blog/2013/10/18/single-page-webapps-in-clojurescript-with-pedestal.html
- break subcomponents into separate projects
- make starter a template
